version: '2'
services:
    fettlepath-app:
        image: fettlepath
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://fettlepath-mysql:3306/fettlepath?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://fettlepath-elasticsearch:9200
        ports:
            - 8080:8080
    fettlepath-mysql:
        extends:
            file: mysql.yml
            service: fettlepath-mysql
    fettlepath-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: fettlepath-elasticsearch
